payment/urls.py
from django.urls import path
from .views import (
    CreateCheckoutSessionView,
    ItemLandingPageView,
    SuccessView,
    CancelView,
)

app_name = 'payment'

urlpatterns = [
    path('item/<int:pk>/', ItemLandingPageView.as_view(), name='landing-page'),
    path('buy/<pk>/', CreateCheckoutSessionView.as_view(), name='buy'),
    path('cancel/', CancelView.as_view(), name='cancel'),
    path('success/', SuccessView.as_view(), name='success'),

]

stripe_payment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('payment.urls'))
]

payment/models.py
from django.db import models

products/models.py
from django.db import models


class Item(models.Model):
    name = models.CharField(max_length=90)
    description = models.TextField()
    price = models.PositiveIntegerField(default=0) #cent

    def __str__(self):
        return self.name

    def get_display_price(self):
        return "{0:.2f}".format(self.price / 100)

payment/views.py
from django.shortcuts import render
from django.conf import settings
from django.views import View
from django.views.generic import TemplateView
from django.http import JsonResponse
import stripe
from django.shortcuts import get_object_or_404
from products.models import Item

stripe.api_key = settings.STRIPE_SECRET_KEY


class SuccessView(TemplateView):
    template_name = 'payment/success.html'


class CancelView(TemplateView):
    template_name = 'payment/cancel.html'


class ItemLandingPageView(TemplateView):
    template_name = 'payment/index.html'

    def get_context_data(self, **kwargs):
        item_id = kwargs['pk']
        item = get_object_or_404(Item, pk=item_id)
        context = super(ItemLandingPageView, self).get_context_data(**kwargs)
        context.update({
            "item": item,
            "STRIPE_PUBLIC_KEY": settings.STRIPE_PUBLIC_KEY
        })
        return context


class CreateCheckoutSessionView(View):
    def get(self, request, *args, **kwargs):
        item_id = self.kwargs['pk']
        item = get_object_or_404(Item, pk=item_id)
        YOUR_DOMAIN = 'http://0.0.0.0'
        checkout_session = stripe.checkout.Session.create(
            line_items=[
                {
                    'price_data':{
                        'currency': 'usd',
                        'unit_amount': item.price,
                        'product_data':{
                            'name': item.name,
                            #'imates': []
                        },
                    },
                    # Provide the exact Price ID (for example, pr_1234) of the product you want to sell
                    'quantity': 1,
                },
            ],
            mode='payment',
            success_url=YOUR_DOMAIN + '/success/',
            cancel_url=YOUR_DOMAIN + '/cancel/',
            automatic_tax={'enabled': False},
        )
        return JsonResponse({
            'id': checkout_session.id
        })

products/views.py
from django.shortcuts import render

# Create your views here.

templates/payment/cancel.html
Cancel!

templates/payment/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Buy cool new product</title>
    <link rel="stylesheet" href="{% static 'payment/css/style.css' %}">
    <script src="https://js.stripe.com/v3/"></script>
  </head>
  <body>
    <section>
      <div class="product">
        <div class="description">
          <h2>Name: {{ item.name }}</h2>
          <h4>Description: {{ item.description }}</h4>
          <h5>Price: ${{ item.get_display_price }}</h5>
        <button class="pressed-button" type="submit" id="checkout-button">Buy</button>
        </div>
      </div>
    </section>
  {% csrf_token %}
  </body>
  <script type="text/javascript">
      const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
      var stripe = Stripe("{{ STRIPE_PUBLIC_KEY }}");
      var checkoutButton = document.getElementById("checkout-button");
      var api = "{% url 'payment:buy' item.id %}"
  </script>
<script type="text/javascript" src="{% static "payment/js/script.js" %}"></script>
</html>

templates/payment/success.html
Success!